### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by paulgc** [tensorflow/data-validation#10]
Currently, TFDV requires Python 2.7 due to dependency on Apache Beam, which is not compatible with Python 3 yet. 

But Python 3 support should be available very soon, as [Apache Beam is almost Python 3 ready](https://issues.apache.org/jira/browse/BEAM-1251).

**Comment by advancera** [comment]
awesome！

**Comment by SebiSebi** [comment]
This would be highly appreciated!

**Comment by harshini-gadige** [comment]
Added a label "Announcement" which helps to quickly access this by using label filters. Hence closing this.

**Comment by elgalu** [comment]
So this is done? Python 3 support is there now?

**Comment by harshini-gadige** [comment]
> So this is done? Python 3 support is there now?

Not yet. Added a label just to keep this issue tracked. Thank you !

**Comment by nbalusu** [comment]
is there any support for java?

**Comment by katsiapis** [comment]
TFDV 0.13 has support for Python 3.5 [1].

Other version of Python (like 3.6 and 3.7) will follow in future releases (after Beam officially supports them).

Should we close this?

/cc @paulgc 

[1] https://github.com/tensorflow/data-validation/releases/tag/v0.13.0

**Comment by impredicative** [comment]
Issues that are not resolved shouldn't really be closed. I understand there is in some projects a hideous culture of closing stale issues for convenience sake, but the issue then hasn't gone away. It just makes it more difficult for users to find and track the issue.

**Comment by impredicative** [comment]
I think Python 3.6 is expected to be a bare minimum these days.

**Comment by katsiapis** [comment]
3.5 and 3.6 wheels are already available for version 0.13.0 [1].

We will "officially" support 3.5 and 3.6 however after Beam also "officially" supports them.

As such this bug could be considered "closed" from TFDV's perspective.

[1] https://pypi.org/project/tensorflow-data-validation/#files

**Comment by paulgc** [comment]
Currently both TFDV and Beam have wheels for 3.5, 3.6 and 3.7. 

But only 3.5 is "officially" supported in all environments (including Cloud Dataflow).

Closing this bug as from TFDV's perspective we are Python 3 compatible.

**Comment by paulgc** [comment]
If you observe any issues with Python 3 package, feel free to open a new issue.
