### ISSUE TITLE
Missing wheel for Python 3.7 under Windows 

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/data-validation#100]
https://pypi.org/project/tensorflow-data-validation/#files

`tensorflow_data_validation-0.15.0-cp37-cp37m-win_amd64.whl` is missing.

**Comment by caveness** [comment]
As of today's release of TFDV (version 0.21.0), a wheel for Python 3.7 under Windows is now available. See https://pypi.org/project/tensorflow-data-validation/0.21.0/#files.
