### ISSUE TITLE
Facets don't render in M80 release of Chrome.

### ISSUE THREAD

**Issue by jarokaz** [tensorflow/data-validation#108]
tfdv.visualize_statistics() does not render after upgrading to Chrome M80.

Environment:
- JupyterLab - GCP Cloud AI Platform Notebooks
- MacOS Catalina
- Chrome - Version 80.0.3987.87 (Official Build) (64-bit)
- TFDV 0.15.0

Chrome 80 was released on Feb 4th.

**Comment by Bobgy** [comment]
I got the same problem, also filed an issue in facets repo.
https://github.com/PAIR-code/facets/issues/207

I think the fix should be done in tfdv by injecting the polyfill

**Comment by Bobgy** [comment]
These two commits by me fixed this issue:
https://github.com/tensorflow/data-validation/commit/50d988baf897044056285df9d86f10a096c93f7b
https://github.com/tensorflow/data-validation/commit/8cb3ca836a64d36a5c57d6d01775c0f5d789117b
