### ISSUE TITLE
Statistics visualization doesn't work in Firefox

### ISSUE THREAD

**Issue by advancera** [tensorflow/data-validation#11]
tfdv.visualize_statistics(train_stats) display nothing except a line.
I print 'train_stats', it does contain the stats i wanted.
so i think the steps before "tfdv.visualize_statistics(train_stats)" is all normal.
My browser is firefox.
where the problem is?

**Comment by paulgc** [comment]
TFDV uses [Facets](https://github.com/PAIR-code/facets) for statistics visualization which currently works only in Chrome ([see issue here](https://github.com/PAIR-code/facets/issues/26)).

**Comment by advancera** [comment]
> TFDV uses [Facets](https://github.com/PAIR-code/facets) for statistics visualization which currently works only in Chrome ([see issue here](https://github.com/PAIR-code/facets/issues/26)).

Thank you for your reply, it’s really great!

**Comment by harshini-gadige** [comment]
Closing this issue as it has been resolved/answered.

**Comment by jameswex** [comment]
If you add
"<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/webcomponents-lite.js"></script>" as the first statement in the facets_html in the visualize_statistics method, above the <link> element, then it should work in Firefox

**Comment by rmothukuru** [comment]
@advancera ,
Can you please confirm if @jameswex's code has resolved your issue.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by joshtemple** [comment]
Is it possible to implement @jameswex's fix for this in `visualize_statistics`? I'm experiencing this issue on Firefox in the Kubeflow Pipelines web UI.

**Comment by jameswex** [comment]
Note that the correct webcomponents version is now <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script> if you want to use my solution.

**Comment by Nithanaroy** [comment]
It is now not working in Chrome v80 as well

https://colab.research.google.com/drive/1MI6jxx0n7RB4mEDAX7Jl9nOJx2uGRqOU is a quick demo of the same

**Comment by kenviku** [comment]
The visualizations are not working on latest Chrome release.
Chrome: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by ndni** [comment]
unfortunately not working either in the current latest Chrome release (Version 81.0.4044.92 (Build oficial) (64 bits))

**Comment by lassehh** [comment]
Can confirm what @kenviku  and @ndni are saying. I got it working inside VS Codes notebook editor, tho.
