### ISSUE TITLE
AttributeError: module 'tensorflow_data_validation' has no attribute 'validate_tfexamples_in_tfrecord'

### ISSUE THREAD

**Issue by mybluedog24** [tensorflow/data-validation#116]
Hi, I'm following the tutorial here: https://www.tensorflow.org/tfx/data_validation/get_started
But when I try to run the code:
```Scala
   options = tfdv.StatsOptions(schema=schema)
   anomalous_example_stats = tfdv.validate_tfexamples_in_tfrecord(
       data_location=input, stats_options=options)
```
It shows error `AttributeError: module 'tensorflow_data_validation' has no attribute 'validate_tfexamples_in_tfrecord'`. My version is 0.21.5.

**Comment by caveness** [comment]
Hi -- There was an error in our documentation. `validate_tfexamples_in_tfrecord` should be `validate_examples_in_tfrecord` (see [source](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/utils/validation_lib.py#L39)). We've submitted a [fix](https://github.com/tensorflow/data-validation/commit/58b1b31a798894c0b39586d2a970773a6cf00573) to the Get Started guide (it may take a day or so for that fix to make it onto the tensorflow.org website). Sorry for the inconvenience, and thanks for reporting the issue.
