### ISSUE TITLE
AttributeError: module 'pyarrow.types' has no attribute 'is_large_list' [while running 'GenerateStatistics/RunStatsGenerators/GenerateSlicedStatisticsImpl/TopKUniquesStatsGenerator/ToTopKTuples']

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/data-validation#118]
In the [TFDV Tutorial](https://colab.sandbox.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/data_validation/tfdv_basic.ipynb) which is present in [Tensorflow.org](https://www.tensorflow.org/tfx/tutorials/data_validation/tfdv_basic#compute_and_visualize_statistics), the error, 

`AttributeError: module 'pyarrow.types' has no attribute 'is_large_list' [while running 'GenerateStatistics/RunStatsGenerators/GenerateSlicedStatisticsImpl/TopKUniquesStatsGenerator/ToTopKTuples']` 

has occurred while executing the command, 

`train_stats = tfdv.generate_statistics_from_csv(data_location=TRAIN_DATA)`.

The documentation should be changed such that entire Tutorial runs without error.

**Comment by xyuzh** [comment]
@rakeshmothukuru1 you may need to restart the runtime after install/update pyarrow

**Comment by Tasfia-Ara** [comment]
Does this issue still need work?

**Comment by pindinagesh** [comment]
Hi @rakeshmothukuru1 

Could you please try with this code [snippet](https://wjones127.github.io/samples/pyarrow-gandiva-docs-v3/_modules/pyarrow/types.html#is_large_list) about pyarrow.types' has no attribute 'is_large_list and see if it helps in resolving your issue? closing this issue for now, Please feel free to reopen if this still exist. Thanks!
