### ISSUE TITLE
ImportError: cannot import name types

### ISSUE THREAD

**Issue by bartcode** [tensorflow/data-validation#12]
I tried both compiling tensorflow_data_validation from the git repository and installing it through pip, but both result in the error below. Am I missing something or could this be a bug?

```text
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-ff8693e3a039> in <module>()
----> 1 import tensorflow_data_validation as tfdv
      2 import os

/path/to/python2.7/site-packages/tensorflow_data_validation/__init__.py in <module>()
     16 
     17 # Import stats API.
---> 18 from tensorflow_data_validation.api.stats_api import GenerateStatistics
     19 from tensorflow_data_validation.api.stats_api import StatsOptions
     20 

/path/to/python2.7/site-packages/tensorflow_data_validation/api/stats_api.py in <module>()
     48 import collections
     49 import apache_beam as beam
---> 50 from tensorflow_data_validation import types
     51 from tensorflow_data_validation.statistics import stats_impl
     52 from tensorflow_data_validation.statistics.generators import common_stats_generator

ImportError: cannot import name types
```

**Comment by paulgc** [comment]
Can you verify if you have `types.py` file in `/path/to/python2.7/site-packages/tensorflow_data_validation/`?

**Comment by bartcode** [comment]
I have checked this and it's there.

**Comment by bartcode** [comment]
Just noticed I'm only getting this error when I import `tensorflow_data_validation` through iPython. Using the `python` binary, it works.

**Comment by paulgc** [comment]
Does your iPython use the same python environment where the TFDV import works? Or do you have multiple python environments?

**Comment by bartcode** [comment]
It's the same environment. In order to validate this, I uninstalled the package and imported TFDV. It then shows `ModuleNotFoundError` in both places.

**Comment by bartcode** [comment]
I got it to work. It appears as if I incorrectly installed the Python 2 kernel for iPython. Thanks for looking, though!

**Comment by dsvolk** [comment]
I have the same issue. @bartcode could you please comment on how you made it work? I have already double-checked I am using the python=2.7 kernel with TFDV in my Jupyter notebook but I am still getting this error.

**Comment by nabilblk** [comment]
Restarting `jupyter` resolve the issue for me .
