### ISSUE TITLE
Will Avro data connector ever be supported? 

### ISSUE THREAD

**Issue by dbustosp** [tensorflow/data-validation#125]
I would like to know if data-connector for Avro will be supported in the near future? 

https://stackoverflow.com/questions/62156582/custom-snapshot-data-validation-with-tfdv-using-avro

**Comment by caveness** [comment]
If you convert the Avro data to Arrow RecordBatches (TFDV's core statistics generation API uses an Arrow RecordBatch to represent a batch of input examples), you can use TFDV with that data. See TFDV's [Get Started guide](https://www.tensorflow.org/tfx/data_validation/get_started#writing_custom_data_connector) for more info.

IIUC, it looks like there was some work done in Arrow to provide an Avro->Arrow connector (see [PR](https://github.com/apache/arrow/pull/1026)), but I don't believe that has been finished. TFDV is not planning to provide a decoder or convenience methods akin to [`generate_statistics_for_tfrecord()`](https://github.com/tensorflow/data-validation/blob/9c6c074965f8339e3e9d1468da810544326dd5d9/tensorflow_data_validation/utils/stats_gen_lib.py#L51) or [`generate_statistics_from_csv()`](https://github.com/tensorflow/data-validation/blob/9c6c074965f8339e3e9d1468da810544326dd5d9/tensorflow_data_validation/utils/stats_gen_lib.py#L115) for Avro format.

Please re-open if this doesn't address your question.
