### ISSUE TITLE
validate_statistics() does not use DatasetConstraints when identifying anomalies

### ISSUE THREAD

**Issue by thisisandreeeee** [tensorflow/data-validation#127]
Python: 3.7.5
TFDV: 0.15.0

I want to identify when my dataset contains fewer rows than expected. I am attempting to do so by configuring the `DatasetConstraint` message of the schema protobuf. However, this does not seem to work.

Code to reproduce the issue:

```python
df = pd.DataFrame({"age": [15, 20, 25]})
stats = tfdv.generate_statistics_from_dataframe(df)
schema = tfdv.infer_schema(stats)
schema.dataset_constraints.min_examples_count = 4
tfdv.display_anomalies(tfdv.validate_statistics(stats, schema))
```

Instead of flagging the dataset as anomalous, this indicates that there are `No anomalies found`. Am I missing something?

**Comment by caveness** [comment]
Thanks for opening this issue. There was a bug in `display_anomalies()` that caused it to ignore dataset-level anomalies (in your code, `validate_statistics()` should return a result that includes the expected dataset-level anomaly).

We've submitted a change to fix the bug (see https://github.com/tensorflow/data-validation/commit/07d1dc69cceec353abbb9799dbc2e7a020ceccd2). Thanks again for reporting the problem!

**Comment by thisisandreeeee** [comment]
This is not a bug in `display_anomalies()`. If you were to inspect the anomalies protobuf, you would find that the `AnomalyInfo` message is empty as well. The following code snippet replicates this:

```python
df = pd.DataFrame({"age": [15, 20, 25]})
stats = tfdv.generate_statistics_from_dataframe(df)
schema = tfdv.infer_schema(stats)
schema.dataset_constraints.min_examples_count = 4
print(tfdv.validate_statistics(stats, schema).anomaly_info) # should not be empty {}
```

**Comment by caveness** [comment]
Thanks for following up. The dataset-level anomaly that we expect in your code should be included in the `dataset_anomaly_info` field of the anomalies proto (as opposed to the `anomaly_info` field) (see https://github.com/tensorflow/metadata/blob/eef318be9d4f3e11b073ad8865b5802f70a4508a/tensorflow_metadata/proto/v0/anomalies.proto#L234-L235). 

If you look in the `dataset_anomaly_info` field of the anomalies proto that `validate_statistics()` returns in your code snippet, do you see the expected anomaly?

**Comment by thisisandreeeee** [comment]
I do not see the expected anomaly in the `dataset_anomaly_info` field. Are you able to replicate this on your machine, or is this just me? 😅

**Comment by caveness** [comment]
I think I see the problem. Support for validating `min_examples_count` was added in TFDV version 0.21.0, so TFDV 0.15.0 does not support it. When running your code snippet with the current version of TFDV (i.e., 0.22.0), I get the expected dataset-level anomaly.

(Note that the fix to `display_anomalies()` noted above was submitted last week, after 0.22.0 was released, so you would need to build from master to get that.)

**Comment by thisisandreeeee** [comment]
I see, that works. Thank you @caveness
