### ISSUE TITLE
Pinned Pandas <1 versioning

### ISSUE THREAD

**Issue by casassg** [tensorflow/data-validation#129]
Hi there, I was wondering if it would be possible to upgrade the setup.py pinned dependencies to accept pandas 1.0.X. It includes a few performance upgrades and this version pin is blocking us on upgrading our local version of Pandas to tap into those performance upgrades.

Is there any specific reason why Pandas is pinned to <1?

**Comment by caveness** [comment]
Hi -- Thanks for opening this. We've updated TFDV's setup.py to modify the Pandas dependency version. See https://github.com/tensorflow/data-validation/commit/8e43d424a6064e9626a00b2ef9db826baa2ab25d.

**Comment by casassg** [comment]
Is there any plans for a new release to include this relaxed dependency?

**Comment by caveness** [comment]
TFDV should have a point release go out soon (I expect this week) that will include this.
