### ISSUE TITLE
Error while using tfdv.generate_statistics_from_csv('path_to_csv_file')

### ISSUE THREAD

**Issue by akki3d76** [tensorflow/data-validation#13]
I got a error when using generate_statistics_from_csv() 

train_stats = tfdv.generate_statistics_from_csv('data_1.csv')
(the path to data is correct)

**Error- ValueError: No line was found. [while running 'DecodeData/ParseCSVRecords']**

**Comment by sudroy** [comment]
Would it be possible to share the first few lines of the csv file ? You can obfuscate the data if it is sensitive.

**Comment by paulgc** [comment]
A possible reason for this error is your CSV file having multi-line records. Currently TFDV uses Apache Beam for reading the input data which doesn't have support for multi-line CSV files.

Can you check if your file has multi-line records?

**Comment by harshini-gadige** [comment]
@akki3d76  - Hi, is this still an issue ? If so, please update. Feel free to close this issue if it no longer exists. Thank you !

**Comment by akki3d76** [comment]
sorry for a late response ..... yeah my data had multi line records !!
