### ISSUE TITLE
validate_statistics does not support struct_stats

### ISSUE THREAD

**Issue by nathanlubchenco** [tensorflow/data-validation#134]
When using the validate_statistics api on some actual data, we noticed that `struct_stats` are not supported. 

https://github.com/tensorflow/data-validation/blob/v0.22.2/tensorflow_data_validation/api/validation_api.py#L499-L506

My understanding is that `struct_stats` include data represented as tensors which are a critical for data type for a number of use cases.

**Comment by caveness** [comment]
Thanks for raising this -- the warning this raises is obsolete, and has been removed (https://github.com/tensorflow/data-validation/commit/484f1e4332fd3b3ba809b3c9f24dc9815c9358f2). It was added before support for schema inference and data validation for struct stats was added in TFDV, but it was not removed when such support was added.
