### ISSUE TITLE
Open multiple .tfrecord

### ISSUE THREAD

**Issue by alelouis** [tensorflow/data-validation#14]
Hello, 

Great work on tfdv.
Is there a way to open multiple .tfrecord files as would behave a tf.data.TFRecordDataset(filenames) ? 
filenames being a list of string containing filename strings.
Large datasets are often stored via numerous .tfrecord files..

Thank you.

**Comment by paulgc** [comment]
You can already generate statistics over multiple files by specifying a file pattern for the `data_location` argument in `generate_statistics_from_tfrecord` method. The pattern can contain glob characters (`*`, `?`, and `[...]` sets).

**Comment by alelouis** [comment]
That's right thank you :)
