### ISSUE TITLE
Example of updating schema in TFX

### ISSUE THREAD

**Issue by albertnanda** [tensorflow/data-validation#144]
I have created a schema using SchemaGen. I want to update one of the fields from required to optional. How can I do that?
[https://www.tensorflow.org/tfx/tutorials/tfx/components_keras](url) in this tutorial, every field is required. How can I make one of the fields optional.

Another question is how do I access the "domain" information from context.show(schema_gen.outputs['schema'])
 programmatically.

**Comment by Mikehem** [comment]
# first get the feature from the schema
feature = tfdv.get_feature(schema, <feature name>) # this will be the column
# for changing from required to optional add a value between 0.0 to 1.0
feature.presence.min_fraction = 0.9
# for changing from optional to required
feature.presence.min_fraction = 1.0
# display the schema to check if the changes have occured as desired
tfdv.display_schema(schema)

**Comment by rmothukuru** [comment]
@albertnanda,
Can you please let us know if @Mikehem's comment worked for you. Thanks!

**Comment by albertnanda** [comment]
It works, closing this issue
