### ISSUE TITLE
FLOAT_TYPE_SMALL_FLOAT schema validation error message is wrong 

### ISSUE THREAD

**Issue by kennysong** [tensorflow/data-validation#148]
Hi! The error message for an out-of-domain float seems to copy the outlier value twice, rather than printing the FloatDomain's min value.

See the duplicate `-12345.6`:

```
description: "Unexpectedly low values: -12345.6<-12345.6(upto six significant digits)"
severity: ERROR
short_description: "Out-of-range values"
reason {
  type: FLOAT_TYPE_SMALL_FLOAT
  short_description: "Out-of-range values"
  description: "Unexpectedly low values: -12345.6<-12345.6(upto six significant digits)"
}
```

**Comment by rmothukuru** [comment]
@kennysong,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by kennysong** [comment]
Here's a somewhat [minimal example in Colab](https://colab.research.google.com/drive/14bBjXRDRPdnt7G9Cj61fpw4a0VhdSjNg?usp=sharing).

Look at the anomaly for the `sepal_length` feature.

**Comment by brills** [comment]
Thanks. this is indeed a bug. Will fix.
