### ISSUE TITLE
Wrong documentation for validate_instance()

### ISSUE THREAD

**Issue by kennysong** [tensorflow/data-validation#149]
In the [TFDV Get Started](https://www.tensorflow.org/tfx/data_validation/get_started#inferring_a_schema_over_the_data) page, it states that:

> TFDV also provides the `validate_instance` function for identifying whether an individual example exhibits anomalies when matched against a schema. To use this function, the example must be a dict mapping feature names to numpy arrays of feature values.

However, `validate_instance()` does not work on dictionaries. It only works on Arrow RecordBatches.

**Comment by gaikwadrahul8** [comment]
@kennysong  

I think we have updated our TFDV documentation page so could you please check once our TFDV documentation page [here](https://www.tensorflow.org/tfx/data_validation/get_started#inferring_a_schema_over_the_data) and also you'll find our all available TFDV Modules and Functions [here](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv), please let's know have we taken care about issue or not ?

Thank you !

**Comment by kennysong** [comment]
Looks like `validate_instance()` was removed from the documentation, so LGTM to close this issue.
