### ISSUE TITLE
DOMAIN_INVALID_FOR_TYPE for categorical int domain

### ISSUE THREAD

**Issue by kennysong** [tensorflow/data-validation#154]
I think there's a bug when validating statistics with a categorical int feature – it (incorrectly?) raises an `DOMAIN_INVALID_FOR_TYPE` anomaly.

[Here's a short notebook](https://colab.research.google.com/drive/1qhjsHddYfJqjpZaDWoLqBR_pF8Rgn4In?usp=sharing) that replicates this.

(This was copied out of a comment from [a closed issue](https://github.com/tensorflow/data-validation/issues/153#issuecomment-753573380).)

**Comment by arghyaganguly** [comment]
while replicating the code in the colab notebook mentioned by @kennysong , i encountered a new issue:- 

versions in use:-
tensorflow :- 2.3.2
tensorflow-data-validation :- 0.26.0
apache-beam :- 2.27.0

import pandas as pd
**import tensorflow_data_validation as tfdv**

AttributeError                            Traceback (most recent call last)
<ipython-input-17-42749874f2cd> in <module>()
      1 import pandas as pd
----> 2 import tensorflow_data_validation as tfdv
      3 print(tfdv.__version__)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/__init__.py in <module>()
     22 
     23 # Import stats API.
---> 24 from tensorflow_data_validation.api.stats_api import GenerateStatistics
     25 from tensorflow_data_validation.api.stats_api import WriteStatisticsToBinaryFile
     26 from tensorflow_data_validation.api.stats_api import WriteStatisticsToText

/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/api/stats_api.py in <module>()
     49 import apache_beam as beam
     50 import pyarrow as pa
---> 51 from tensorflow_data_validation.statistics import stats_impl
     52 from tensorflow_data_validation.statistics import stats_options
     53 

/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/statistics/stats_impl.py in <module>()
     31 from tensorflow_data_validation.statistics.generators import basic_stats_generator
     32 from tensorflow_data_validation.statistics.generators import image_stats_generator
---> 33 from tensorflow_data_validation.statistics.generators import lift_stats_generator
     34 from tensorflow_data_validation.statistics.generators import natural_language_domain_inferring_stats_generator
     35 from tensorflow_data_validation.statistics.generators import sparse_feature_stats_generator

/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/statistics/generators/lift_stats_generator.py in <module>()
    108 
    109 # Beam counter to track the number of non-utf8 values.
--> 110 _NON_UTF8_VALUES_COUNTER = beam.metrics.Metrics.counter(
    111     constants.METRICS_NAMESPACE, 'num_non_utf8_values_lift_generator')
    112 

AttributeError: module 'apache_beam' has no attribute 'metrics'

**Comment by paulgc** [comment]
This is due to TFDV not automatically inferring categorical INTs in the schema.
