### ISSUE TITLE
Can we display/Store anomalies as HTML

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/data-validation#158]
Hi, Is there any way that we store anomalies as HTML object.

If anomalies found then displaying dataframe as HTML object?
If no anomalies displaying it as HTML object?

Else store this anomalies to variable?

**Comment by caveness** [comment]
Hi -- Can you tell me a bit more about why you'd like to store anomalies as an HTML object?

TFDV includes the [display_anomalies](https://github.com/tensorflow/data-validation/blob/1cf52211c19e9334cd3d1dd8aed614ca4a99e237/tensorflow_data_validation/utils/display_util.py#L155) utility function, but I don't know if it would work for your use case, as it is intended for displaying anomalies in a Jupyter notebook.

**Comment by cah-aswini-jalla** [comment]
I am trying to use this html object to store into a tool neptune. For which I can store html objects as Artifact into neptune.

So I need the output in any format as dataframe/image/html/text

And Am using PyCharm IDE where i couldn't display.

**Comment by caveness** [comment]
Thanks for your reply and the additional information. We don't have that currently in TFDV, but we're planning to add functionality that would give the anomalies output as a Pandas DataFrame to TFDV relatively soon. It sounds like that would fit your use case. I'll comment on this Issue when that functionality goes into TFDV.

**Comment by caveness** [comment]
We've added the get_anomalies_dataframe utility function (see [commit](https://github.com/tensorflow/data-validation/commit/ef66b9d2e2c52bf71efcb0078e621b0892e8fff7)), which you can use to get the anomalies results as a DataFrame.
