### ISSUE TITLE
TFDV anomalies shows column dropped for all Features in dataset

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/data-validation#161]
Hi, I have been using tensorflow data validation for my dataset to analyze anomalies for new dataset in comparison to old dataset. 

There was a new column and unexpected values in new dataset which I expect to display as anomalies for validate statistics but I have seen many other anomalies in description for all features which are shown as 

**Short Description:** Column dropped
**Long Description:** The feature was present in fewer examples than expected: minimum fraction = 1.000000, actual = 0.999997

I could not understand what is wrong with all features in dataset. Everything seems normal when I had gone through dataset.

Can you explain a bit more about this anomalies  and how could I resolve them.

**Commands Used:**
new_dataset_stats = tfdv.generate_statistics_from_dataframe(df_new_data)
old_dataset_stats = tfdv.generate_statistics_from_dataframe(df_old_data)

schema = tfdv.infer_schema(old_dataset_stats)
anomalies = tfdv.validate_statistics(statistics=new_dataset_stats, schema=schema)
display_anomalies(anomalies)

Thanks.
![anomalies](https://user-images.githubusercontent.com/76488911/110236005-7e236d80-7f59-11eb-9a31-f785bae14946.PNG)

**Comment by arghyaganguly** [comment]
@cah-aswini-jalla ,for the features which are dropped with the reason(analogy long description) :-  The feature was present in fewer examples than expected: minimum fraction = 1.000000, actual = 0.999997,
does they have any missing values in the new dataset?
You can also manually adjust the minimum fraction according to the business logic/requirement .
For example :-  If you feel the feature "CONTRACT" can have 10% missing values in your new dataset if compared to the old dataset, we can set that up manually as :- 


```
schema = tfdv.load_schema_text(schema_location) #load schema from serialized location
#now update the feature so that it is required in 90% of the cases :-
contract_feature = tfdv.get_feature(schema,'CONTRACT')
contact_feature.presence.min_fraction = 0.9

#once you are satisfied with the schema, write the schema file to its location(serialized) :
schema = tfdv.write_schema_text(schema,schema_location)

#revalidate the statistics to view updated anomalies :
updated_anomalies = tfdv.validate_statistics(statistics=new_dataset_stats, schema=schema)
tfdv.display_anomalies(anomalies))
```

**Comment by arghyaganguly** [comment]
@cah-aswini-jalla , please confirm whether the above comment has been helpful.

**Comment by cah-aswini-jalla** [comment]
Hi, What does missing value mean in your case. In my dataset there are no NA values. And more over it display as No Anomalies initially but later when I have updated a single value of a column it displayed all this anomalies as Column Dropped

**When no updates are made in dataset:**
df_new_data['is_weekend'].value_counts()

0    1796353
1     118634
Name: is_weekend, dtype: int64

schema = tfdv.infer_schema(old_dataset_stats)
anomalies = tfdv.validate_statistics(statistics=new_dataset_stats, schema=schema)
display_anomalies(anomalies)
>> No Anomalies

**When Updated a value in is_weekend column:**
df_old_data.at['12', 'is_weekend'] = 100
df_old_data['is_weekend'].value_counts()

0.0      6842358
1.0       445408
100.0          1
Name: is_weekend, dtype: int64

schema = tfdv.infer_schema(old_dataset_stats)
anomalies = tfdv.validate_statistics(statistics=new_dataset_stats, schema=schema)
display_anomalies(anomalies)

>> Displays anomalies attached in previous comment.


I Expected it to display only Anomaly for column is_weekend because there was unexpected new value as 100. But I didn't understand why all other columns got this anomaly.

Else is there any way I don't want to check for min_presence for features because I don't want to write this manually for all columns in dataset.

**Comment by caveness** [comment]
Hi -- If I understand what you're describing correctly, there is one example in your new dataset that doesn't contain the features for which you are seeing the Column Dropped anomalies in your results; that example only contains the `is_weekend` feature. That is why you are getting anomalies for the features other than `is_weekend` when you validate the new dataset stats.

If you don't want to check for minimum presence for certain features, you would need to remove/modify the `min_fraction` field for those features in your schema. You could try doing so programmatically by using the [`schema_transformations` argument](https://github.com/tensorflow/data-validation/blob/79bfb37efeddae2b1fb7c39dc04ac9003c22621f/tensorflow_data_validation/api/validation_api.py#L81) of `tfdv.infer_schema` if you don't want to do so manually.
