### ISSUE TITLE
What was the motivation of selected drift/skew comparators?

### ISSUE THREAD

**Issue by michalbrys** [tensorflow/data-validation#170]
Are there any publications/docs explaining the motivation behind
using `jensen_shannon_divergence` / `infinity_norm` for the Data Drift / Training-Serving Skew detection?
Since there are many approaches, I'm wondering why those 2 were selected.
Regards,
Michal Brys

**Comment by peteboothroyd** [comment]
I've seen some discussion in this paper:  https://mlsys.org/Conferences/2019/doc/2019/167.pdf eg. around interpretability of the alerts.

**Comment by caveness** [comment]
Closing per the prior comment. The linked doc is the closest thing to the requested info available.
