### ISSUE TITLE
pip install not working from jupyter

### ISSUE THREAD

**Issue by DeekshitY** [tensorflow/data-validation#178]
pip install tensorflow-data-validation
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation (from versions: none)
ERROR: No matching distribution found for tensorflow-data-validation
Note: you may need to restart the kernel to use updated packages.

I tried many options but it didn't work. 

I am using a mac.

**Comment by arghyaganguly** [comment]
@DeekshitY , which version of python do you have in your current kernel?
We need to have Python >=3.6, <4 installed as documented in [link](https://pypi.org/project/tensorflow-data-validation/).

**Comment by DeekshitY** [comment]
> @DeekshitY , which version of python do you have in your current kernel?
> We need to have Python >=3.6, <4 installed as documented in [link](https://pypi.org/project/tensorflow-data-validation/).

Hi , I have python, 3.6.8 in my kernel.

**Comment by arghyaganguly** [comment]
@DeekshitY , are you using a conda environment?
Please provide your pip list output and the version of pip you're using.

**Comment by DeekshitY** [comment]
Package                 Version
----------------------- -------------------
absl-py                 0.12.0
anyio                   3.0.1
appnope                 0.1.2
argon2-cffi             20.1.0
astunparse              1.6.3
async-generator         1.10
attrs                   21.2.0
Babel                   2.9.1
backcall                0.2.0
bazel                   0.0.0.20200723
bitarray                2.1.0
bleach                  3.3.0
Bottleneck              1.3.2
cachetools              4.2.2
certifi                 2021.5.30
cffi                    1.14.5
chardet                 4.0.0
cx-Oracle               8.2.1
cycler                  0.10.0
decorator               4.4.2
defusedxml              0.7.1
distlib                 0.3.2
entrypoints             0.3
findspark               1.4.2
flatbuffers             1.12
fuzzywuzzy              0.18.0
gast                    0.4.0
google-auth             1.30.1
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
grpcio                  1.34.1
h5py                    3.1.0
htmlmin                 0.1.12
idna                    2.10
ImageHash               4.2.0
impala                  0.2
impyla                  0.17.0
ipykernel               5.5.5
ipython                 7.23.1
ipython-genutils        0.2.0
ipywidgets              7.6.3
jedi                    0.18.0
Jinja2                  3.0.1
joblib                  1.0.1
json5                   0.9.5
jsonschema              3.2.0
jupyter-client          6.1.12
jupyter-console         6.4.0
jupyter-core            4.7.1
jupyter-server          1.7.0
jupyterlab              3.0.16
jupyterlab-pygments     0.1.2
jupyterlab-server       2.5.2
jupyterlab-widgets      1.0.0
keras-nightly           2.5.0.dev2021032900
Keras-Preprocessing     1.1.2
kiwisolver              1.3.1
Markdown                3.3.4
MarkupSafe              2.0.1
matplotlib              3.4.2
matplotlib-inline       0.1.2
missingno               0.4.2
mistune                 0.8.4
multimethod             1.4
nbclassic               0.2.8
nbclient                0.5.3
nbconvert               6.0.7
nbformat                5.1.3
nest-asyncio            1.5.1
networkx                2.5.1
notebook                6.4.0
numpy                   1.19.5
oauthlib                3.1.1
opt-einsum              3.3.0
packaging               20.9
pandas                  1.2.4
pandas-profiling        3.0.0
pandas-read-xml         0.3.1
pandocfilters           1.4.3
parso                   0.8.2
pexpect                 4.8.0
phik                    0.11.2
pickleshare             0.7.5
Pillow                  8.2.0
pip                     21.1.2
prometheus-client       0.10.1
prompt-toolkit          3.0.18
protobuf                3.17.2
ptyprocess              0.7.0
pure-sasl               0.6.2
pyarrow                 4.0.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.20
pydantic                1.8.2
Pygments                2.9.0
pyparsing               2.4.7
pyrsistent              0.17.3
python-dateutil         2.8.1
pytz                    2021.1
PyWavelets              1.1.1
PyYAML                  5.4.1
pyzmq                   22.0.3
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
scipy                   1.6.3
seaborn                 0.11.1
Send2Trash              1.5.0
setuptools              56.0.0
six                     1.15.0
sniffio                 1.2.0
tangled-up-in-unicode   0.0.7
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.5.0
tensorflow-estimator    2.5.0
termcolor               1.1.0
terminado               0.9.1
testpath                0.4.4
thrift                  0.11.0
thrift-sasl             0.4.3
tornado                 6.1
tqdm                    4.61.0
traitlets               5.0.5
typing-extensions       3.7.4.3
urllib3                 1.26.5
visions                 0.7.1
wcwidth                 0.2.5
webencodings            0.5.1
websocket-client        1.0.0
Werkzeug                2.0.1
wheel                   0.36.2
widgetsnbextension      3.5.1
wrapt                   1.12.1
xmltodict               0.12.0
zipfile36               0.1.3
Note: you may need to restart the kernel to use updated packages.

pip 21.1.2 from /usr/local/Cellar/jupyterlab/3.0.16/libexec/lib/python3.9/site-packages/pip (python 3.9)
Note: you may need to restart the kernel to use updated packages.

I think you are right ins saying python version, 
from platform import python_version

print(python_version())
I am getting 3.9.5

but in my local and all I have it downgraded but, my jupyter env is not taking python 3.8.10 
can you help me in that area may be ?

**Comment by DeekshitY** [comment]
I have installed conda and then used this link From there I was able to install it. 

Thanks For the help.
