### ISSUE TITLE
Getting infinity_norm or jensen_shannon value

### ISSUE THREAD

**Issue by nishantsethi** [tensorflow/data-validation#181]
In the documentation of TFDV I am not able to find the way by which we can store the jensen_shannon value. On every run, I want to store these values even if they don't go above the threshold.

**Comment by caveness** [comment]
Hi -- TFDV doesn't an API for getting these values in the absence of an anomaly. One possible (quasi-) workaround would be to have a pipeline in which you set the infinity norm and jensen shannon thresholds to 0.0 and get the values from resulting anomalies.

**Comment by caveness** [comment]
Closing per comment above.
