### ISSUE TITLE
No TFDV releases on pypi for python 3.8/3.9

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/data-validation#185]
https://pypi.org/project/tensorflow-data-validation/#files contains wheels for py 3.6 (macosx/linux) and 3.7 (win) but not 3.8/3.9. Can wheels for all supported python versions be added?

**Comment by zoyahav** [comment]
All expected binaries have been added (macos, linux, win, 3.6, 3.7, 3.8).
Note that TFDV doesn't currently release binaries for 3.9, see the ["Programming Language" section](https://pypi.org/project/tensorflow-data-validation).

**Comment by arghyaganguly** [comment]
@0x0badc0de , please confirm if we can close this issue based on the reply from @zoyahav .Thank you.

**Comment by 0x0badc0de** [comment]
@arghyaganguly given the version for 3.9 is not supposed to be released, sure, this one can be closed.
