### ISSUE TITLE
TFDV treat 0 as missing value when dataset is in json format

### ISSUE THREAD

**Issue by miaoelenawang** [tensorflow/data-validation#187]
When I generate statistics from `json` dataset, for numerical column, the zero is treated as missing value. And if the dataset is `tfrecord`, tfdv can correctly treat zero as zero.

**Comment by arghyaganguly** [comment]
@miaoelenawang , please provide a  code snippet and the associated error trace to help us expedite the debug process.Thanks.

**Comment by miaoelenawang** [comment]
Hi, I think there are additional steps in the pipeline, I will investigate more. I am going to close the ticket for now. Will update when I find more details.
