### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation (from versions: none)

### ISSUE THREAD

**Issue by tassosblackg** [tensorflow/data-validation#200]
I've tried to install tfdv using `pip3 install tensorflow-data-validation`

`python version is 3.9`
`tensorflow version is 2.5`
` working on Manjaro 21.1.6`

And I got this error:
> ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation (from versions: none)
> ERROR: No matching distribution found for tensorflow-data-validation

What is causing this problem?

**Comment by caveness** [comment]
TFDV is not yet supported on Python3.9. To install the latest version of TFDV (i.e., 1.4.0), you'll need to use Python3.7 or 3.8.
