### ISSUE TITLE
Missing support for M1 Mac

### ISSUE THREAD

**Issue by utkarshagarwal** [tensorflow/data-validation#205]
Installation fails on M1 mac for tfx-bsl, tft and tfdv.

**Comment by pindinagesh** [comment]
@utkarshagarwal 

Sorry for late response.

Have you tried with this [installation guide](https://github.com/tensorflow/tfx-bsl/#tfx-basic-shared-libraries)? and M1 Macs are not supported for tfx-bsl as it mentioned [here](https://gist.github.com/davidxia/468dadb7ffcb0e1c4a28947bcff0482c), correct me if I am missing something. Thanks!

**Comment by utkarshagarwal** [comment]
@pindinagesh 
Yeah, I tried the installation guide but failed as I am using M1 Mac. Linux x86 VM on UTM also fails as it tries to leverage instruction set not supported by base CPU.

Any idea if these libs will be supported on new M1 Macs?

**Comment by parnell** [comment]
Any update on this issue? It would be nice to be able to use TF data validation on the M1. Especially as this hardware is becoming more and more present as older models get phased out.

**Comment by gaikwadrahul8** [comment]
@parnell, @utkarshagarwal 

I'm really sorry to inform you that, at the moment unfortunately we don't support TFT, TFX and TFDV for M1 Mac, We are currently working on this issue, and will have an update in the fairly near future. In the meantime, some users have reported success with Rosetta. Other options include using a VM. We understand that neither of those is ideal

You can also check on our Tensorflow Forum, same discussion is going on [here](https://discuss.tensorflow.org/t/i-want-to-use-the-tfx-1-6-1-on-mac-m1-max/8110) so you can check latest update about it.

Supported platforms :

TFDV is tested on the following 64-bit operating systems:

macOS 10.14.6 (Mojave) or later.
Ubuntu 16.04 or later.
Windows 7 or later.

**Comment by parnell** [comment]
Thank you for the update @gaikwadrahul8. Disappointing of course but I understand. Checking the discussion on the Tensorflow Forum it seems they recognize this as a real issue and that it is already impacting some Alphabet teams. So hopefully TFT, TFX, and TFDV will get supported soon. I'll be eagerly waiting.

**Comment by gaikwadrahul8** [comment]
@parnell 

We completely understand Mac M1 users situation for TFT, TFX, and TFDV support and We are currently working on this issue, and will have an update in the fairly near future 

Thank you!

**Comment by tangm** [comment]
Have created https://github.com/tensorflow/data-validation/pull/251 . If/when https://github.com/tensorflow/tfx-bsl/pull/73 goes through, it should allow tfdv to be built.

**Comment by ee07dazn** [comment]
Any update on where we are with this ? Our entire team (company) is on Mac M1s so finding it extremely difficult to build something using TFDV.

**Comment by MohamadOHijazi** [comment]
> If possible, we should also enable building for ARM64 on Linux.

Actually, This makes sense when You use TFX and tfdv in dataset preparation for model training you need to apply the operations on the new data aka inference data. and Linux and ARM64 are the perfect lightweight OS for an edge machine.
at least they should release a light version.
