### ISSUE TITLE
[BUG] visualize_statistics ignores  lhs_name/rhs_name parameters

### ISSUE THREAD

**Issue by mancosta** [tensorflow/data-validation#220]
In version 1.9 of tfdv (I think the problem was in previous versions too), when I do something like the snippet below, `lhs_name` and `rhs_name` are ignored, displaying the default names: `lhs_statistics` and `rhs_statistics` instead of `TRAIN_SET` and `TEST_SET`.
```python
    tfdv.visualize_statistics(
        lhs_statistics=partition_stats,
        lhs_name="TRAIN_SET",
        rhs_statistics=partition_to_compare_stats,
        rhs_name="TEST_SET"
    )
```

Making a little deep dive, it seems the problem comes from `_get_combined_statistics` function. It just try to use `lhs_statistics.datasets[0].name` and `rhs_statistics.datasets[0].name` as names, ignoring the ones passed by the user.

**Comment by caveness** [comment]
Thanks for raising this issue. We [modified the relevant documentation](https://github.com/tensorflow/data-validation/commit/78a74b98afefb6163d64d9fc885448ca73ee14b6) to clarify how lhs_name and rhs_name are used.
