### ISSUE TITLE
The potential security vulnerability on the joblib library

### ISSUE THREAD

**Issue by abdel91** [tensorflow/data-validation#226]
The package joblib from version 0 and before 1.2.0 are vulnerable to Arbitrary Code Execution via the pre_dispatch flag in Parallel() class due to the eval() statement.

My PR:
[https://github.com/tensorflow/data-validation/pull/225
](https://github.com/tensorflow/data-validation/pull/225
)
More infos:
[https://github.com/joblib/joblib/issues/1128](https://github.com/joblib/joblib/issues/1128)

**Comment by singhniraj08** [comment]
@abdel91, Thank you for the contribution. Once reviewed, the PR will be merged.

**Comment by eslamkarim** [comment]
hello,
any news on this? we would love to use the library but blocked waiting for this fix to go through.
