### ISSUE TITLE
import tensorflow_data_validation error

### ISSUE THREAD

**Issue by eric-tc** [tensorflow/data-validation#23]
Hi when i'm importing tensorflow_data_visualization i'm getting the following error: 

i am on mac OS X El Capitan using anaconda python 2.7.12 enviroment

How can i resolve this.

 _import tensorflow_data_validation
  File "/Users/Eric/anaconda2/lib/python2.7/site-packages/tensorflow_data_validation/__init__.py", line 18, in <module>
    from tensorflow_data_validation.api.stats_api import GenerateStatistics
  File "/Users/Eric/anaconda2/lib/python2.7/site-packages/tensorflow_data_validation/api/stats_api.py", line 51, in <module>
    from tensorflow_data_validation.statistics import stats_impl
  File "/Users/Eric/anaconda2/lib/python2.7/site-packages/tensorflow_data_validation/statistics/stats_impl.py", line 24, in <module>
    from tensorflow_data_validation.statistics.generators import stats_generator
  File "/Users/Eric/anaconda2/lib/python2.7/site-packages/tensorflow_data_validation/statistics/generators/stats_generator.py", line 57, in <module>
    from tensorflow_metadata.proto.v0 import schema_pb2
  File "/Users/Eric/anaconda2/lib/python2.7/site-packages/tensorflow_metadata/proto/v0/schema_pb2.py", line 23, in <module>
    x01(\x01\x12\x11\n\tmin_count\x18\x02 \x01(\x03\"\x8c\x03\n\x06\x44omain\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x31\n\x04ints\x18\x02 \x01(\x0b\x32!.tensorflow.metadata.v0.IntDomainH\x00\x12\x35\n\x06\x66loats\x18\x03 \x01(\x0b\x32#.tensorflow.metadata.v0.FloatDomainH\x00\x12\x37\n\x07strings\x18\x04 \x01(\x0b\x32$.tensorflow.metadata.v0.StringDomainH\x00\x12\x33\n\x05\x62ools\x18\x05 \x01(\x0b\x32\".tensorflow.metadata.v0.BoolDomainH\x00\x12\x38\n\x08\x66\x65\x61tures\x18\x0c \x01(\x0b\x32$.tensorflow.metadata.v0.StructDomainH\x00\x12Q\n\x18\x64istribution_constraints\x18\x06 \x01(\x0b\x32/.tensorflow.metadata.v0.DistributionConstraintsB\r\n\x0b\x64omain_info\"!\n\x0cInfinityNorm\x12\x11\n\tthreshold\x18\x01 \x01(\x01\"P\n\x11\x46\x65\x61tureComparator\x12;\n\rinfinity_norm\x18\x01 \x01(\x0b\x32$.tensorflow.metadata.v0.InfinityNorm*u\n\x0eLifecycleStage\x12\x11\n\rUNKNOWN_STAGE\x10\x00\x12\x0b\n\x07PLANNED\x10\x01\x12\t\n\x05\x41LPHA\x10\x02\x12\x08\n\x04\x42\x45TA\x10\x03\x12\x0e\n\nPRODUCTION\x10\x04\x12\x0e\n\nDEPRECATED\x10\x05\x12\x0e\n\nDEBUG_ONLY\x10\x06*J\n\x0b\x46\x65\x61tureType\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\t\n\x05\x42YTES\x10\x01\x12\x07\n\x03INT\x10\x02\x12\t\n\x05\x46LOAT\x10\x03\x12\n\n\x06STRUCT\x10\x04\x42!\n\x1aorg.tensorflow.metadata.v0P\x01\xf8\x01\x01')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'_

Thanks

**Comment by harshini-gadige** [comment]
@eric-tc  Hi, did you get a chance to try with protobuf>=3.6.0 ?  Please keep us posted.

**Comment by eric-tc** [comment]
Hi @harshini-gadige 
yes upgrading protobuf resolve my problem. Sorry for not posting. 

Thanks @paulgc
