### ISSUE TITLE
tfdv.generate_statistics_from_csv not working anymore with current branch

### ISSUE THREAD

**Issue by AndreaPi** [tensorflow/data-validation#28]
I installed the latest version of `tensorflow-data-validation` with

`pip install tensorflow-data-validation
`

I'm not able anymore to generate statistics from .csv files. On a file of mine which worked, I get now

```
startt = time.time()
train_stats = tfdv.generate_statistics_from_csv(TRAIN_DATA)
trainstats_time = time.time() - startt
print(trainstats_time)
AttributeErrorTraceback (most recent call last)
<ipython-input-3-5f22d5888316> in <module>()
      1 startt = time.time()
----> 2 train_stats = tfdv.generate_statistics_from_csv(TRAIN_DATA)
      3 trainstats_time = time.time() - startt
      4 print(trainstats_time)

/usr/local/lib/python2.7/dist-packages/tensorflow_data_validation/utils/stats_gen_lib.pyc in generate_statistics_from_csv(data_location, column_names, delimiter, output_path, stats_options, pipeline_options)
    149                                                 delimiter=delimiter)
    150         | 'GenerateStatistics' >> stats_api.GenerateStatistics(stats_options)
--> 151         | 'WriteStatsOutput' >> beam.io.WriteToTFRecord(
    152             output_path,
    153             shard_name_template='',

/usr/local/lib/python2.7/dist-packages/apache_beam/pvalue.pyc in __or__(self, ptransform)
    109 
    110   def __or__(self, ptransform):
--> 111     return self.pipeline.apply(ptransform, self)
    112 
    113 

/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.pyc in apply(self, transform, pvalueish, label)
    465     if isinstance(transform, ptransform._NamedPTransform):
    466       return self.apply(transform.transform, pvalueish,
--> 467                         label or transform.label)
    468 
    469     if not isinstance(transform, ptransform.PTransform):

/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.pyc in apply(self, transform, pvalueish, label)
    475       try:
    476         old_label, transform.label = transform.label, label
--> 477         return self.apply(transform, pvalueish)
    478       finally:
    479         transform.label = old_label

/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.pyc in apply(self, transform, pvalueish, label)
    511       transform.type_check_inputs(pvalueish)
    512 
--> 513     pvalueish_result = self.runner.apply(transform, pvalueish)
    514 
    515     if type_options is not None and type_options.pipeline_type_check:

/usr/local/lib/python2.7/dist-packages/apache_beam/runners/runner.pyc in apply(self, transform, input)
    191       m = getattr(self, 'apply_%s' % cls.__name__, None)
    192       if m:
--> 193         return m(transform, input)
    194     raise NotImplementedError(
    195         'Execution of [%s] not implemented in runner %s.' % (transform, self))

/usr/local/lib/python2.7/dist-packages/apache_beam/runners/runner.pyc in apply_PTransform(self, transform, input)
    197   def apply_PTransform(self, transform, input):
    198     # The base case of apply is to call the transform's expand.
--> 199     return transform.expand(input)
    200 
    201   def run_transform(self, transform_node):

/usr/local/lib/python2.7/dist-packages/tensorflow_data_validation/api/stats_api.pyc in expand(self, dataset)
    197             num_values_histogram_buckets=\
    198                 self._options.num_values_histogram_buckets,
--> 199             epsilon=self._options.epsilon),
    200 
    201         # Create numeric stats generator.

/usr/local/lib/python2.7/dist-packages/tensorflow_data_validation/statistics/generators/common_stats_generator.pyc in __init__(self, name, schema, num_values_histogram_buckets, epsilon)
    229     # Initialize quantiles combiner.
    230     self._quantiles_combiner = quantiles_util.QuantilesCombiner(
--> 231         num_values_histogram_buckets, epsilon)
    232 
    233   # Create an accumulator, which maps feature name to the partial stats

/usr/local/lib/python2.7/dist-packages/tensorflow_data_validation/utils/quantiles_util.pyc in __init__(self, num_quantiles, epsilon)
     38     self._num_quantiles = num_quantiles
     39     self._epsilon = epsilon
---> 40     self._quantiles_spec = analyzers._QuantilesCombinerSpec(
     41         num_quantiles=num_quantiles, epsilon=epsilon,
     42         bucket_numpy_dtype=np.float32, always_return_num_quantiles=True)

AttributeError: 'module' object has no attribute '_QuantilesCombinerSpec'
```

**Comment by paulgc** [comment]
TFDV currently depends on Tensorflow Transform package. TFDV 0.9.0 requires Tensorflow Transform 0.9.0. This issue is due to pip installing the latest version of Transform (0.11.0). We will be releasing a new version of TFDV (0.11.0) which is compatible with Transform 0.11.0.

In the meantime, you can force install Transform 0.9.0 using the following command to avoid this error.
`pip install tensorflow_transform==0.9.0`

**Comment by AndreaPi** [comment]
Thanks, this fixed the error.

**Comment by ndni** [comment]
Good morning, 
generate_statistics_from_csv works well with a dataset with previous versión (tfdv.version.__version__ '0.15.0', Python 3.6.9), but with the latest version (0.21.5, Python 3.7.6) the following error is reported: 'NoneType' object has no attribute 'get_metric_cell'
Thanks

~\Anaconda3\envs\P37\lib\site-packages\tensorflow_data_validation\utils\stats_gen_lib.py in generate_statistics_from_csv(data_location, column_names, delimiter, output_path, stats_options, pipeline_options, compression_type)
    195             shard_name_template='',
    196             coder=beam.coders.ProtoCoder(
--> 197                 statistics_pb2.DatasetFeatureStatisticsList)))
    198   return load_statistics(output_path)
    199 

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\pipeline.py in __exit__(self, exc_type, exc_val, exc_tb)
    479   def __exit__(self, exc_type, exc_val, exc_tb):
    480     if not exc_type:
--> 481       self.run().wait_until_finish()
    482 
    483   def visit(self, visitor):

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\pipeline.py in run(self, test_runner_api)
    459           self.to_runner_api(use_fake_coders=True),
    460           self.runner,
--> 461           self._options).run(False)
    462 
    463     if self._options.view_as(TypeOptions).runtime_type_check:

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\pipeline.py in run(self, test_runner_api)
    472       finally:
    473         shutil.rmtree(tmpdir)
--> 474     return self.runner.run_pipeline(self, self._options)
    475 
    476   def __enter__(self):

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\direct\direct_runner.py in run_pipeline(self, pipeline, options)
    180       runner = BundleBasedDirectRunner()
    181 
--> 182     return runner.run_pipeline(pipeline, options)
    183 
    184 

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in run_pipeline(self, pipeline, options)
    484 
    485     self._latest_run_result = self.run_via_runner_api(pipeline.to_runner_api(
--> 486         default_environment=self._default_environment))
    487     return self._latest_run_result
    488 

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in run_via_runner_api(self, pipeline_proto)
    492     # TODO(pabloem, BEAM-7514): Create a watermark manager (that has access to
    493     #   the teststream (if any), and all the stages).
--> 494     return self.run_stages(stage_context, stages)
    495 
    496   @contextlib.contextmanager

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in run_stages(self, stage_context, stages)
    581               stage,
    582               pcoll_buffers,
--> 583               stage_context.safe_coders)
    584           metrics_by_stage[stage.name] = stage_results.process_bundle.metrics
    585           monitoring_infos_by_stage[stage.name] = (

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in _run_stage(self, worker_handler_factory, pipeline_components, stage, pcoll_buffers, safe_coders)
    902         cache_token_generator=cache_token_generator)
    903 
--> 904     result, splits = bundle_manager.process_bundle(data_input, data_output)
    905 
    906     def input_for(transform_id, input_id):

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in process_bundle(self, inputs, expected_outputs)
   2103 
   2104     with UnboundedThreadPoolExecutor() as executor:
-> 2105       for result, split_result in executor.map(execute, part_inputs):
   2106 
   2107         split_result_list += split_result

~\Anaconda3\envs\P37\lib\concurrent\futures\_base.py in result_iterator()
    596                     # Careful not to keep a reference to the popped future
    597                     if timeout is None:
--> 598                         yield fs.pop().result()
    599                     else:
    600                         yield fs.pop().result(end_time - time.monotonic())

~\Anaconda3\envs\P37\lib\concurrent\futures\_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

~\Anaconda3\envs\P37\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\utils\thread_pool_executor.py in run(self)
     42       # If the future wasn't cancelled, then attempt to execute it.
     43       try:
---> 44         self._future.set_result(self._fn(*self._fn_args, **self._fn_kwargs))
     45       except BaseException as exc:
     46         # Even though Python 2 futures library has #set_exection(),

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in execute(part_map)
   2100           self._progress_frequency, self._registered,
   2101           cache_token_generator=self._cache_token_generator)
-> 2102       return bundle_manager.process_bundle(part_map, expected_outputs)
   2103 
   2104     with UnboundedThreadPoolExecutor() as executor:

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in process_bundle(self, inputs, expected_outputs)
   2023             process_bundle_descriptor_id=self._bundle_descriptor.id,
   2024             cache_tokens=[next(self._cache_token_generator)]))
-> 2025     result_future = self._worker_handler.control_conn.push(process_bundle_req)
   2026 
   2027     split_results = []  # type: List[beam_fn_api_pb2.ProcessBundleSplitResponse]

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py in push(self, request)
   1356       self._uid_counter += 1
   1357       request.instruction_id = 'control_%s' % self._uid_counter
-> 1358     response = self.worker.do_instruction(request)
   1359     return ControlFuture(request.instruction_id, response)
   1360 

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\sdk_worker.py in do_instruction(self, request)
    350       # E.g. if register is set, this will call self.register(request.register))
    351       return getattr(self, request_type)(getattr(request, request_type),
--> 352                                          request.instruction_id)
    353     else:
    354       raise NotImplementedError

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\sdk_worker.py in process_bundle(self, request, instruction_id)
    384         with self.maybe_profile(instruction_id):
    385           delayed_applications, requests_finalization = (
--> 386               bundle_processor.process_bundle(instruction_id))
    387           monitoring_infos = bundle_processor.monitoring_infos()
    388           monitoring_infos.extend(self.state_cache_metrics_fn())

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\bundle_processor.py in process_bundle(self, instruction_id)
    815       for op in self.ops.values():
    816         _LOGGER.debug('finish %s', op)
--> 817         op.finish()
    818 
    819       return ([self.delayed_bundle_application(op, residual)

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\operations.py in finish(self)
    970   def finish(self):
    971     for wkey, value in self.table.items():
--> 972       self.output_key(wkey, value[0], value[1])
    973     self.table = {}
    974     self.key_count = 0

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\operations.py in output_key(self, wkey, accumulator, timestamp)
    978       value = accumulator
    979     else:
--> 980       value = self.combine_fn_compact(accumulator)
    981 
    982     if self.is_default_windowing:

~\Anaconda3\envs\P37\lib\site-packages\tensorflow_data_validation\statistics\stats_impl.py in compact(self, accumulator)
    716       accumulator: _CombinerStatsGeneratorsCombineFnAcc
    717       ) -> _CombinerStatsGeneratorsCombineFnAcc:
--> 718     self._maybe_do_batch(accumulator, force=True)
    719     self._num_compacts.inc(1)
    720     return accumulator

~\Anaconda3\envs\P37\lib\site-packages\tensorflow_data_validation\statistics\stats_impl.py in _maybe_do_batch(self, accumulator, force)
    649     """
    650     if self._should_do_batch(accumulator, force):
--> 651       self._combine_batch_size.update(accumulator.curr_batch_size)
    652       self._combine_byte_size.update(accumulator.curr_byte_size)
    653       if len(accumulator.input_tables) == 1:

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\metrics\execution.py in __call__(self, value)
    196     tracker = get_current_tracker()
    197     if tracker is not None:
--> 198       tracker.update_metric(self.typed_metric_name, value)
    199 
    200   def __reduce__(self):

~\Anaconda3\envs\P37\lib\site-packages\apache_beam\runners\worker\statesampler_slow.py in update_metric(self, typed_metric_name, value)
     57 
     58   def update_metric(self, typed_metric_name, value):
---> 59     self.current_state().metrics_container.get_metric_cell(
     60         typed_metric_name).update(value)
     61 

AttributeError: 'NoneType' object has no attribute 'get_metric_cell'

**Comment by mail2chromium** [comment]
> Thanks, this fixed the error.

Can you please jump into my problem Sir @AndreaPi @paulgc [Issue#121](https://github.com/tensorflow/data-validation/issues/121#issue-599093141)?
