### ISSUE TITLE
Missing API for manually setting domain

### ISSUE THREAD

**Issue by AdrianLsk** [tensorflow/data-validation#30]
Hi,  thank you for a terrific library!

I  ran into an edge case, where `infer_schema` doesn' t detect any domain. This leads to a missing attribute `domain_info`. Therefore, I would like to be able to set it manually.

This now means to fiddle around with the protobuffer, which doens't have the most user-friendly API.

Would it be possible to have a python function for example `set_domain` to avoid the protobuffer API?

**Comment by paulgc** [comment]
Newly released TFDV 0.11.0 has a `set_domain` method which can used to set the domain of a feature.

**Comment by AdrianLsk** [comment]
@paulgc Great, thanks!
