### ISSUE TITLE
AttributeError: 'module' object has no attribute '_QuantilesCombinerSpec'

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/data-validation#34]
While using `tfdv.generate_statistics_from_csv()` I get the error AttributeError: 'module' object has no attribute '_QuantilesCombinerSpec', as noted [in](https://github.com/tensorflow/data-validation/issues/31).
This seems to be caused by Tensorflow transform changing the _QuantilesCombinerSpec in analyzers.py to QuantilesCombiner, which I think can be fixed by install tensorflow-transform==0.9.0.
I think the dependency on Tensorflow-transform in setup.py should be set <0.11 to avoid this error surfacing when installing via pip.

**Comment by paulgc** [comment]
Can you upgrade to TFDV 0.11.0 (which depends on TFT 0.11.0)? This issue should not occur once you upgrade to 0.11.0.

**Comment by harshini-gadige** [comment]
@peteboothroyd  As asked above, have you tried with the latest TFDV version ? Please post here.

**Comment by peteboothroyd** [comment]
Yes this is fine now thanks
