### ISSUE TITLE
Can't find the "Schema change generator" code

### ISSUE THREAD

**Issue by yonromai** [tensorflow/data-validation#39]
In the [TFX Paper](http://stevenwhang.com/tfx_paper.pdf), under the "Data Validation" section, it is said:
> In some cases the anomalies correspond to a natural evolution of the data, and the appropriate action is to change the schema (rather than fix the data). To accommodate this option, **our component generates for each anomaly a corresponding schema change that can bring the schema up-to-date**

Besides the textual [Reason description](https://github.com/tensorflow/metadata/blob/master/tensorflow_metadata/proto/v0/anomalies.proto#L145), is this schema change generation code open sourced? 
I spent some time looking in the doc and exploring the Python API but couldn't find anything.

**Comment by paulgc** [comment]
@yonromai The schema change generation is not open-sourced yet. But we plan to open-source it soon.

**Comment by yonromai** [comment]
That's helpful, thank you @paulgc. Any idea what "soon" means? Doesn't need to be super accurate, but a ball park ETA would be useful for us.

**Comment by paulgc** [comment]
@yonromai We recently added support for [updating an existing schema](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/api/validation_api.py#L119) to conform with new statistics. Does that address your usecase?

**Comment by yonromai** [comment]
Indeed this looks great, thanks!
