### ISSUE TITLE
tfdv.validate_statistics drops existing column and adds it as a new column

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/data-validation#4]
Awesome TFX tool! Thank you for the great work.

I stepped through the tfx data-validation example with my own data and noticed that the a column got dropped and added as a new column when I ran `anomalies = tfdv.validate_statistics(eval_stats, schema)`

In my example example data, my training and eval data have the same columns, I just added additional keys to different columns in the eval data.

When I then run 

```
eval_stats = tfdv.generate_statistics_from_csv(EVAL_DATA)
anomalies = tfdv.validate_statistics(eval_stats, schema)
tfdv.display_anomalies(anomalies)
```  

I receive the table output below like

```
Feature name		Anomaly short description            Anomaly long description
f_key			New column 				       New column (column in data but not in schema): f_key
...
f_key			Column dropped 			       Column is completely missing
```

`f_key` is in the schema.

```
feature {
  name: "f_key"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
```

What causes the anomaly info (drop/new) for an existing column?

**Comment by paulgc** [comment]
@hanneshapke Closing this issue for now. Feel free to reopen this in case you are able to reproduce the odd behavior.

**Comment by npoly** [comment]
@jackhawa Can you provide a minimal repro so that we can investigate further?
