### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow_data_validation

### ISSUE THREAD

**Issue by uguisu** [tensorflow/data-validation#40]
Hi All,

I'm facing following problem when I import tensorflow_data_validation in my source code:
`ImportError: cannot import name pywrap_tensorflow_data_validation`

Dig into the code, I find `pywrap_tensorflow_data_validation` has been lost (or removed, maybe), whereas this program(model) is required by following code:
- https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/api/validation_api.py#L26
- https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/build_pip_package.sh#L22

Could someone kindly let me know where can I find `pywrap_tensorflow_data_validation.py`?

Thanks.

**Comment by paulgc** [comment]
Can you share the following information:

- Your OS Platform and Distribution
- Your Python version
- TFDV installed from source or pip?
- Do you have tensorflow installed?

**Comment by uguisu** [comment]
I'm working under:
- Ubuntu mate 18.04.1 x64
- Python 2.7.15.rc1
- I use `pip install tensorflow-data-validation` to install TFDV, and the version is 0.11.0
  To run the example of _Chicago Taxi_, I also clone the whole git repo from GitHub. The example works fine for me when I run it on local machine.
- Tensorflow also been installed by pip, the version is 1.12.0

I think you can reproduce this issue by create new python program and try to import TFDV. For example:
`import tensorflow_data_validation as tfdv`

**Comment by hgadig** [comment]
This should work fine with tensorflow-data-validation version 0.13.1 and latest tensorflow version.
Please check and let us know if the issue still persist.

**Comment by uguisu** [comment]
It works fine for me. Thanks.

Confirmed on:
- Ubuntu mate 18.04.1 x64
- Python 2.7.15.rc1
- Tensorflow 1.13.1
- tfdv 0.13.1
