### ISSUE TITLE
Inconsistency between statistics and inferred schema

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/data-validation#41]
Good morning,

I have a dataset that contains many features, one of which is a list of 5 strings.
I have doubled check that for every examples I do have not more or less than 5 distinct strings for this feature. I am also generating this dataset with a dataflow pipeline, dumping the data both in tfrecords and in BigQuery. I have doubled check in BigQuery as well.
Now when I use tfdv and generate statistics and infer a schema I get these:
For `statistics.pb`:
```
name: "tracks"
type: STRING
string_stats {
  common_stats {
    num_non_missing: 6998315
    min_num_values: 5
    max_num_values: 5
    avg_num_values: 5.0
    num_values_histogram {
...
```

for `schema.pb`:
```
feature {
  name: "tracks"
  value_count {
    min: 1
  }
  type: BYTES
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
```

Now when I convert my schema to FeatureSpec I get a `VarLenFeature` though I was expecting a `FixedLenFeature` since I "know" that the shape should be [5].
This is the only feature I have with a shape >1. All the others are basically 1 string per example and I get `FixedLenFeature` for them, as expected.

Does anyone know why this schema was generated like this?

**Comment by hgadig** [comment]
Is this working fine with the latest TFDV and Tensorflow versions? If not, could you please share the following information.

OS Platform and Distribution
Python version
TFDV installed from source or pip
Do you have tensorflow installed?

**Comment by paulgc** [comment]
This should get fixed after https://github.com/tensorflow/data-validation/commit/94f5366940ad83e2a5146f5893387f4b8d982b83
