### ISSUE TITLE
overflow encountered in long_scalars

### ISSUE THREAD

**Issue by cbreuel** [tensorflow/data-validation#48]
I am getting the following error when running tfdv.generate_statistics_from_csv() in my dataset:

`/usr/local/lib/python2.7/dist-packages/tensorflow_data_validation/statistics/generators/numeric_stats_generator.py:108: RuntimeWarning: overflow encountered in long_scalars
  numeric_stats.sum_of_squares += v * v`

**Comment by mschonwe** [comment]
I'm experiencing a similar overflow error (getting stats from TFRecord file):
```
import tensorflow_data_validation as tfdv
stats = tfdv.generate_statistics_from_tfrecord(data_location='/path/tfrec-train-00067-of-00100')
```

Error:
```
basic_stats_generator.py:221: RuntimeWarning: overflow encountered in float_scalars
  self.sum_of_squares += v * v
```
The dataset is audio examples (float32) <=17sec and associated labels.

Is there something different that needs to be done to handle these types of examples?

**Comment by mschonwe** [comment]
I implemented a work-around that allows the processing to complete.  By initializing the accumulator to float128 it doesn't overflow.  Change made just before this line (https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/generators/basic_stats_generator.py#L214)
```
    # Iterate through the value array and update the partial stats.
    v = np.float128(0.0)
    for v in value:
```

**Comment by caveness** [comment]
A commit was recently made to address these overflow warnings: https://github.com/tensorflow/data-validation/commit/20273e96786d2d4887f7408f657a9e3eee61d3af. Please let us know if the issue persists.
