### ISSUE TITLE
Make desired_batch_size argument public in GenerateStatistics API

### ISSUE THREAD

**Issue by AdrianLsk** [tensorflow/data-validation#53]
Hi, currently it's not possible to state `desired_batch_size` in the public API of [GenerateStatistics](https://github.com/tensorflow/data-validation/blob/6776903698e357541f35da0d1703efe4010ac627/tensorflow_data_validation/api/stats_api.py#L79).

Though the functionality is implemented in [`_BatchedCombineFnWrapper`](https://github.com/tensorflow/data-validation/blob/6776903698e357541f35da0d1703efe4010ac627/tensorflow_data_validation/statistics/stats_impl.py#L337)

The easiest way to use it is by adding it to `StatsOptions` and pass it [here](https://github.com/tensorflow/data-validation/blob/6776903698e357541f35da0d1703efe4010ac627/tensorflow_data_validation/statistics/stats_impl.py#L108) to `_BatchedCombineFnWrapper`.

The desired result would look like:
```python
class GenerateSlicedStatisticsImpl(beam.PTransform):

  def __init__(
      self,
      options = stats_options.StatsOptions(desired_batch_size=100)
      ):
    self._options = options
   ....
    for generator in stats_generators:
      ....       
          _BatchedCombineFnWrapper(generator,
           desired_batch_size=self._options.desired_batch_size)).with_hot_key_fanout(fanout))
```

Or is there a reason why it's hidden at the moment?

Thanks.

**Comment by paulgc** [comment]
@AdrianLsk The batch size option is now exposed with 15bebb05f7355529898b91c66b3ff9cb965bb393. It will be part of the next release.
