### ISSUE TITLE
is there docs about the statics and math part?

### ISSUE THREAD

**Issue by yupbank** [tensorflow/data-validation#55]
or links to some paper or tech report?

**Comment by paulgc** [comment]
@yupbank You can find the description of the various statistics in the [proto](https://github.com/tensorflow/metadata/blob/master/tensorflow_metadata/proto/v0/statistics.proto). We will work on adding more documentation on the statistics and how we compute them.

**Comment by UsharaniPagadala** [comment]
@yupbank 
Closing this issue as it is resolved.Please feel free to open if this issue still persists.Thanks
