### ISSUE TITLE
Any way to speed up tfdv.TFExampleDecoder?

### ISSUE THREAD

**Issue by cyc** [tensorflow/data-validation#56]
I think most users of this library will most likely be feeding in data from serialized `tf.train.Example`s stored in TFRecords. However, the performance of `tfdv.TFExampleDecoder` may become a bottleneck for some users. If you profile that code, you find that it spends minimal amounts of time deserializing the data and the vast majority of its time building the output dictionary and instantiating numpy arrays. The problem is exacerbated for workflows with hundreds or thousands of scalar features, where the overhead of creating small numpy arrays seems to dominate.

Do you have any tips for what can be done to optimize this part of the TFDV workflow? I've already tried swapping in `tft.coders.ExampleProtoCoder` in cases where the schema is known in advance, but it does not seem to provide very much of a performance gain (about 10%).

**Comment by paulgc** [comment]
@cyc We have replaced the coder with a [faster variant](https://github.com/tensorflow/data-validation/commit/78107d9c41a182585b1c5b7d89b8a0448c83a2c8) implemented in C++ and callable from Python using SWIG.

Currently you can use this by [building a new wheel from source](https://github.com/tensorflow/data-validation#installing-from-source) and passing it as an extra package when running on Google Cloud (see [related discussion](https://github.com/tensorflow/data-validation/issues/38) on using extra packages). Let us know if you have any issues with building the wheel.

**Comment by cyc** [comment]
Awesome! I will give this a shot!

**Comment by cyc** [comment]
@paulgc, the new decoder works well and thank you for supplying instructions for how to build and run it. From my local benchmarks it appears that it helps significantly for the data that I have been working with.

`TFExampleDecoder` (TFDV 0.13.1): ~280 examples/sec
`TFExampleDecoder` (TFDV 0.14.0.dev0): ~2100 examples/sec
`tf.train.Example.ParseFromString`: ~2750 examples/sec

So the new decoder is around 7-8 times faster than the old one, and very close to the speed of just deserializing the underlying protocol buffer.

From running TFDV on a subset of my dataset on Google Cloud Dataflow, I see the following results:

TFDV 0.13.1: 33 min, 14 sec; **48.4** vCPU-hours
TFDV 0.14.0.dev0: 24 min, 47 sec; **21.5** vCPU-hours

Unfortunately this new decoder doesn't seem to do much to improve my TFT running time or even compute usage, probably because decoding is not actually the bottleneck for that process.

I will go ahead and close this issue as successfully fixed, thank you for your help!

**Comment by paulgc** [comment]
@cyc Thanks for trying it out. Can you share how you used this decoder with TFT?

**Comment by cyc** [comment]
Sure. I just have a PTransform that looks like this:

```python
@beam.typehints.with_output_types(tfdv.types.BeamExample)
@beam.ptransform_fn
def LoadFromTFRecord(pipeline, input_path, validate=True):
    return (
        pipeline
        | 'ReadFromTFRecord' >> beam.io.ReadFromTFRecord(file_pattern=input_path,
                                                         validate=validate,
                                                         coder=tfdv.coders.tf_example_decoder.TFExampleDecoder())
    )
```

The output of this (along with the metadata) is fed into `tft.beam.AnalyzeAndTransformDataset`
