### ISSUE TITLE
Add a tfdv.load_anomalies_text function similar to tfdv.load_schema_text

### ISSUE THREAD

**Issue by loiccordone** [tensorflow/data-validation#57]
Hello,

I'm setting up a TFX pipeline, and I want to analyze the results with TFDV. The SchemaGen component outputs a "schema.pbtxt", which can be loaded then displayed nicely with 
```
schema = tfdv.load_schema_text(os.path.join(PIPELINE_DIR, 'SchemaGen/output/3/schema.pbtxt'))
tfdv.display_schema(schema)
```
As far as I know, there is no function to load the anomalies text file outputted by the ExampleGen component and display it nicely, even though there is a display_anomalies function. Can you add it ?

Thank you !

**Comment by caveness** [comment]
Sure -- we've added `load_anomalies_text` and `write_anomalies_text` in https://github.com/tensorflow/data-validation/commit/61d51fce316d773b43876a80b1cc705435a63352.
