### ISSUE TITLE
Documentation about anomalies and what constraints trigger them

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/data-validation#63]
This issue is maybe related to https://github.com/tensorflow/data-validation/issues/62 where the answer is "We are working on a better documentation".

Generally, I would like to see a list of 
* possible anomalies
* what fields are compared to trigger them (between statistics and schema or statistics and statistics)
* What field in schema is responsible for the constraint (might be the same as above)

Specifically,
I want to protect myself against a integer feature suddenly having 100% of zero values. I am wondering if there is a field in the schema that I can set to validate this?

**Comment by caveness** [comment]
We've added a [TFDV Anomalies Reference document](https://github.com/tensorflow/data-validation/blob/master/g3doc/anomalies.md) to our repo, which lists the anomaly types that TFDV can detect, the schema and statistics fields that are used to detect each anomaly type, and the condition(s) under which each anomaly type is detected.
