### ISSUE TITLE
Custom statistics with CombinerStatsGenerator and sequential data

### ISSUE THREAD

**Issue by TimSmole** [tensorflow/data-validation#67]
Hi!

I would like to use TFDV with sequential data (SequenceExamples stored in TFRecord). Under closed issues (#45) I found that this is currently not yet supported, but that this capability will be added in the future. 

Since it doesn't seem this feature would be added any time soon I tried to use _CombinerStatsGenerator_ for custom statistic generation but it turns out that _input_table_ argument passed to _CombinerStatsGenerator._add_input__ function includes only _context_ features of _SequenceExamples_ stored in my TFRecord file.

Is there a reason for this? Or even more importantly is there a workaround or any other way I can access sequential data inside TFRecord? 

Also does anyone know when we can expect TFDV will include support for sequential data?

Thanks!

**Comment by paulgc** [comment]
Hi Tim,

Currently TFDV doesn't support `SequenceExample`. The `input_table` only has the `context` features as TFDV Decoder would try to parse the serialized `SequenceExample` as `TFExample` and hence ignores the `FeatureLists`. A temporary workaround for handling `SequenceExample` would be to implement a `CustomDecoder` that would decode `SequenceExample` into a flat dictionary representation (which the `GenerateStatistics` API expects). Follow the instructions [here](https://github.com/tensorflow/data-validation/blob/master/g3doc/get_started.md#writing-custom-data-connector) to construct a pipeline with a custom decoder.

We are actively working on adding support for statistics computation over `SequenceExamples` and structured data (e.g., protocol buffers). Moving towards Apache Arrow tables as the in-memory data representation in TFDV was a step towards this direction as we can capture structured data with Arrow tables. We plan to add support for `SequenceExample` in TFDV `0.15`/`0.16` (next release would be `0.14`).

Also, note that in `0.15` we plan to move from the flat dictionary representation to Arrow table. Currently this happens internally in TFDV code where we convert the flat dictionaries to Arrow tables. But we plan to make the `GenerateStatistics` API consume Arrow tables in `0.15`.

**Comment by brills** [comment]
TFDV now supports SequenceExample. Please check tensorflow_data_validation/integration_tests/sequence_example_e2e_test.py for an example.
