### ISSUE TITLE
unable to find reference of from tensorflow_data_validation.pywrap import pywrap_tensorflow_data_validation as pywrap

### ISSUE THREAD

**Issue by satylogin** [tensorflow/data-validation#70]
i was unable to find the reference of 
from tensorflow_data_validation.pywrap import pywrap_tensorflow_data_validation as pywrap.

It is mentioned in arrow_util.py

**Comment by paulgc** [comment]
`pywrap_tensorflow_data_validation` is a shared library that is generated when building TFDV from source. The underlying C++ methods are defined [here](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/arrow/cc/arrow_util.h). You can find the SWIG code [here](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/pywrap/arrow.i) which generates the Python wrappers for invoking the underlying C++ methods.

You can generate the shared library by following the [instructions](https://github.com/tensorflow/data-validation#installing-from-source) to build TFDV from source. Note that the PyPI wheel of TFDV includes the shared library and the Python wrapper.

**Comment by gowtham-kp** [comment]
@satylogin Did that answer your question? Can I close this issue?
