### ISSUE TITLE
Is it possible to pinpoint the exact example that caused the anomalies?

### ISSUE THREAD

**Issue by benjamintanweihao** [tensorflow/data-validation#71]
Currently when generating anomalies, a table is generated like: 

![Tensorflow_Data_Visualization](https://user-images.githubusercontent.com/861236/60426636-a0fb6b80-9c27-11e9-96f8-3e2ceda30e72.png)

However, is there a way to pinpoint the actual example that's causing the problem?

**Comment by caveness** [comment]
TFDV's validation API now has the [IdentifyAnomalousExamples](https://github.com/tensorflow/data-validation/blob/8f64e706875ac49d4935e29b025f0b04cfea35c9/tensorflow_data_validation/api/validation_api.py#L391) transform, which takes as input a PCollection of examples and outputs (anomaly reason, anomalous example) tuples. You can use this transform to identify particular examples that generate anomalies.

TFDV also offers convenience functions for working with this transform: [validate_examples_in_tfrecord](https://github.com/tensorflow/data-validation/blob/8f64e706875ac49d4935e29b025f0b04cfea35c9/tensorflow_data_validation/utils/validation_lib.py#L39) and [validate_examples_in_csv](https://github.com/tensorflow/data-validation/blob/8f64e706875ac49d4935e29b025f0b04cfea35c9/tensorflow_data_validation/utils/validation_lib.py#L109). These functions detect anomalies on a per-example basis. If one of these functions detects anomalous examples, it generates summary statistics regarding the set of examples that exhibit each anomaly. So, you can use these convenience functions to better understand the examples that exhibit a particular anomaly (e.g., the number of examples affected, their value distributions, etc.).

The convenience functions handle reading and decoding data into TFDV's internal format. If you use the transform directly, you will need to take care of reading and decoding the data yourself.

**Comment by gowtham-kp** [comment]
@benjamintanweihao Did that answer your question. Can I close the issue?

**Comment by benjamintanweihao** [comment]
@caveness Thanks! I will try this out.
