### ISSUE TITLE
get_statistics_html should support multiple datasets

### ISSUE THREAD

**Issue by htahir1** [tensorflow/data-validation#74]
Hi there! I was wondering whether get_statistics_html would support a statistics_pb2.DatasetFeatureStatisticsList() that has more than one dataset (currently it throws an exception if this is the case). 

I am raising the issue because my use-case requires me to slice my data into multiple categories (using slice_functions in StatsOptions for GenerateStatistics()). After slicing per category, I would like to see a HTML per category to find how my data behaves per category.

Now, I think this is relatively straightforward - I even implemented a workaround below that just looped through the datasets and created a new HTML for each:

```
stats = load_statistics('...')  # these are statistics with multiple datasets
for stat in stats.datasets:
    stat_listed = statistics_pb2.DatasetFeatureStatisticsList()
    stat_listed.datasets.append(stat)
    with open(os.path.join(out_path, stat.name + '.html'), 'w') as f:
        f.write(get_statistics_html(stat_listed))
```

Is this too much of an edge case for the library, or is it worth a PR? Thanks in advance!

**Comment by brills** [comment]
If you are still interested in it, yes - a PR is welcomed.

**Comment by htahir1** [comment]
Happy to contribute but need some more detail on how I should proceed. The code I outlined above will probably break `visualize_statistics` where `get_statistics_html` is originally called in the source. 

Should the added behavior be a seperate utility function call? Or should the change then propagate down to `visualize_statistics`?

**Comment by brills** [comment]
We currently have tfdv.get_slice_stats which can give you a DatasetFeatureStatisticsList that contains only one entry (the slice that you care about).

you can call get_statistics_html(tfdv.get_slice_stats(your_stats, your_slice_name))
