### ISSUE TITLE
Cannot determine feature type error

### ISSUE THREAD

**Issue by htahir1** [tensorflow/data-validation#77]
Hi! I am getting a strange error while running "StatisticsGen" from the TFX platform. The error is as follows: "TypeError: Cannot determine the type of feature {}. Found values of types 0 and 1.".

The feature in question indeed has values 1 and 0 but I assume that this should be of type integer or if done smartly, boolean. 

After delving into the documentation and code, I do not see how this comes about. Any help would be greatly appreciated! Thanks!

**Comment by paulgc** [comment]
@htahir1 The types 0 and 1 refers to the [proto enum values](https://github.com/tensorflow/metadata/blob/master/tensorflow_metadata/proto/v0/statistics.proto#L86). This error happens when the feature in question has conflicting types. What is your data format (CSV/TFRecord)?

**Comment by htahir1** [comment]
@paulgc thanks for the clarification. the data format is TFRecord coming from a TFX examplegen component

**Comment by paulgc** [comment]
@htahir1  For CSV input, we do the type inference and would automatically cast to FLOAT. But for `tf.Example` we use the types in the proto as such and assume the types are consistent. This error could happen if the feature in question has `int64_list` in one example and `float_list` in another example. Do you expect your data to have this behavior?

**Comment by htahir1** [comment]
@paulgc yes, sometimes I do expect this behavior as the example_gen in TFX also infers TF Example proto's per sample, and therefore sometimes its int64_list and sometimes float_list.

Is there a way to ignore these conflicts, i.e., drop these points when generating statistics? Or at least giving a distribution of how many types each feature type occurs?

**Comment by brills** [comment]
Non-conformant examples cannot be parsed by Tensorflow. That's why TFDV does not bother generating stats for them as they can never be used to train a TF model.
 
https://github.com/tensorflow/tensorflow/blob/605ff0fecfff0f812f3985c8e1002d8b878374cf/tensorflow/core/example/example.proto#L78
