### ISSUE TITLE
How to generate statistics from multiple csv files

### ISSUE THREAD

**Issue by theoqian** [tensorflow/data-validation#81]
The first argument of generate_statistics_from_csv is data_location which is string type. But the description of data_location is 'data_location: The location of the input data files' which indicates that multiple files can be provided. So I wonder how to use generate_statistics_from_csv to read multiple files.

Thanks.

**Comment by caveness** [comment]
Hi -- You can use glob characters in the `data_location` argument. So, if you want to read `input_data1.csv` and `input_data2.csv` from `some_temp_dir`, you would specify '`some_temp_dir/input_data*`' for the `data_location` argument. 

You can look at [test_stats_gen_with_csv_header_in_multiple_files](https://github.com/tensorflow/data-validation/blob/8ffe4f13f59537a4aef3211af3569e54ca3dbf99/tensorflow_data_validation/utils/stats_gen_lib_test.py#L445-L464) for a basic example of specifying multiple input files with `generate_statistics_from_csv`.

**Comment by theoqian** [comment]
> 
> 
> Hi -- You can use glob characters in the `data_location` argument. So, if you want to read `input_data1.csv` and `input_data2.csv` from `some_temp_dir`, you would specify '`some_temp_dir/input_data*`' for the `data_location` argument.
> 
> You can look at [test_stats_gen_with_csv_header_in_multiple_files](https://github.com/tensorflow/data-validation/blob/8ffe4f13f59537a4aef3211af3569e54ca3dbf99/tensorflow_data_validation/utils/stats_gen_lib_test.py#L445-L464) for a basic example of specifying multiple input files with `generate_statistics_from_csv`.

Thanks!
