### ISSUE TITLE
Facets axis labels are not visible in Colab

### ISSUE THREAD

**Issue by ageron** [tensorflow/data-validation#82]
The axis labels are not visible in Colab, due to the color scheme.

See the following screenshot. Note that I selected the text from the end of row 2 to the end of row 3, to highlight the fact that the axis labels are there, but just not visible:

![image](https://user-images.githubusercontent.com/76661/65105063-455ea400-da06-11e9-9b7a-b3672469fc89.png)

You can see this in the [tutorial Colab notebook](https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/data_validation/chicago_taxi.ipynb#scrollTo=JhXQSxJ2dB_6).

**Comment by rcrowe-google** [comment]
It looks like you're using a dark theme in Chrome?  Could you elaborate?

**Comment by ageron** [comment]
Oops, good point, I must have chosen this theme long ago, and forgot about it. I thought this was the default Colab theme. When I change back to the default theme, everything looks fine. Thanks!
Still, it would be nice if the labels were visible in all Colab themes, don't you think?

**Comment by rmothukuru** [comment]
Closing this issue as it has been resolved, from @rcrowe-google's comments. Feel free to reopen if required. Thanks!

**Comment by ageron** [comment]
Hi @rmothukuru ,
I'm not sure I'd say it's fully resolved: it works fine with the default Colab theme, which is of course the most important, but it is unreadable when using the dark theme. I suppose quite a few people use the dark theme. Perhaps slightly changing the color of the axis labels would make them visible in both themes?

**Comment by caveness** [comment]
Facets has opened an issue to track the appearance of Overview in dark mode. See [issue](https://github.com/PAIR-code/facets/issues/197). Since that issue has been opened, I'm closing this one (work to be done is in Facets).
