### ISSUE TITLE
TFDV fails with other compression types

### ISSUE THREAD

**Issue by Arvinds-ds** [tensorflow/data-validation#86]
I have a folder with gzipped csv files and when I run

```
tfdv.generate_statistics_from_csv(LOC, compression_type=CompressionTypes.GZIP)

```
It fails. The reason being while the beam pipeline now supports the GZIP compression type, there is a prior step `get_csv_header` to get the header which does not support other compression types. 

Can this be fixed?

**Comment by paulgc** [comment]
@Arvinds-ds Did you try passing the header using the `column_names` argument? This should avoid invoking the `get_csv_header`.

**Comment by Arvinds-ds** [comment]
Agree..but that impedes discovery of the column names from the file itself. It is a painful workaround :)

**Comment by pindinagesh** [comment]
@Arvinds-ds 

Can you please try with newer version of TFDV which is **TensorFlow Data Validation 1.6.0** and let us know if the issue still persists in newer version. Thanks!

**Comment by andylou2** [comment]
Hi, this has been fixed in https://github.com/tensorflow/data-validation/commit/597e2fda54d8bd30e76dc60dc58487d1b8780b2f
