### ISSUE TITLE
Types missing in documentation / code for tfdv.CombinerStatsGenerator

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/data-validation#87]
Methods in "abstract" classes should use type hinting as it can be hard to create custom implementations (e.g. combiner that derives `tfdv.CombinerStatsGenerator`) without prior reverse engineering of already implemented generators. 

Here is an example:

```
def extract_output(self, accumulator):  
    """Returns result of converting accumulator into the output value.
    Returns:
      A proto representing the result of this stats generator.
    """
```
What `proto` is expected here?  Can I create a custom one or do I have to use `statistics_pb2.DatasetFeatureStatistics` or maybe something else?

Here however:
```
  def merge_accumulators(self, accumulators):
    """Merges several accumulators to a single accumulator value.

    Args:
      accumulators: The accumulators to merge.
```
I have to guess that accumulators might be a list due to the plural form of the variable name, yet `accumulators:List[object]` would be helpful for my IDE.

Etc, you get the picture

**Comment by caveness** [comment]
Hi Christopher -- The code itself should have type hints for tfdv.CombinerStatsGenerator (and the other methods in the abstract classes). See, e.g., [1].

Can you clarify what you're looking at? Is it the API docs?

[1] https://github.com/tensorflow/data-validation/blob/31a60c1986ec1fcd59518deb4aea582530fc62c0/tensorflow_data_validation/statistics/generators/stats_generator.py#L136-L138

**Comment by rmothukuru** [comment]
@wsuchy,
Can you please respond to @caveness's comment. Thanks!

**Comment by wsuchy** [comment]
@rmothukuru can't find it anymore, seems to be related with previous version. I am closing the issue.
