### ISSUE TITLE
infer_schema(..., infer_feature_shape=True) should parse VarLenFeature to SparseFeature

### ISSUE THREAD

**Issue by schmidt-jake** [tensorflow/data-validation#94]
If I understand things correctly, the desired behavior of `infer_schema(..., infer_feature_shape=True)` would be to infer feature shapes for FixedLenFeatures while parsing VarLenFeatures to SparseFeatures in the schema. However, my VarLenFeature currently gets parsed as a Feature with dim=0. Am I understanding this properly / am I doing something wrong?

**Comment by gowthamkpr** [comment]
@JakeTheWise Yes your understanding is right. You can review it and also modify it.

**Comment by npoly** [comment]
Please note that TFDV does not provide any feature-parsing functionality. TFDV can generate an initial schema, which in turn can be fed to other tools (e.g., TFT which uses the schema to drive feature parsing). The shape inference done my TFDV only determines the information stored in the schema.

**Comment by gowthamkpr** [comment]
@JakeTheWise Did it clear your doubt. Can I close this issue?

**Comment by JakeTheWise** [comment]
Not quite. I'm still confused about what is the best practice for handling TFRecords in TFDV that contain variable-length features alongside fixed-length features. I understand TFDV recently added support for sparse features but it's unclear how to use it. Currently I am just clearing the `shape` field of the inferred schema but this feels gross. Can someone advise?

**Comment by gowthamkpr** [comment]
@npoly Can you PTAL. Thanks!

**Comment by npoly** [comment]
@JakeTheWise please help us understand whether the following is correct:

- You run TFDV with infer_feature_shape=True. At this point, this means that the 'shape' stanza in the schema will be populated **only for fixed-length features**. _Is this what you are seeing?_

- You want to use this schema to auto-configure parsing in **TFT**. The latter will handle fixed-length features with a FixedLenFeature parsing spec, and any other feature with the VarLenFeature parsing spec. _Is this what your are seeing_?

Let's pause with these questions to make sure we are on the same page. If the answer to these questions is Yes then the next question is:

-  Is it that TFDV wrongfully infers that some features are fixed-length instead of inferring that they form a SparseFeature?

**Comment by JakeTheWise** [comment]
You run TFDV with infer_feature_shape=True. At this point, this means that the 'shape' stanza in the schema will be populated only for fixed-length features. Is this what you are seeing?

- No. What seems to be happening is that the fixed length features' shapes will be properly inferred, while the variable length features will also have their shape inferred but incorrectly, ie their dimension will be 0. It may be relevant to note that my variable length feature has some examples with length 0.

You want to use this schema to auto-configure parsing in TFT. The latter will handle fixed-length features with a FixedLenFeature parsing spec, and any other feature with the VarLenFeature parsing spec. Is this what you're are seeing?
- I believe that is correct, and the current behavior of TFT. There seems to be some nuance in how this happens, though. Currently, it seems that TFT parses the feature based on the presence or absence of a `shape` stanza in the schema.

So while my answers aren't "yes", your third question is basically what I'm trying to understand: I'm not sure how to get TFDV to properly infer a SparseFeature.

**Comment by npoly** [comment]
Thanks for the clarifications. Currently TFDV does not support the automatic inference of SparseFeature, and this might be hard to implement robustly. One workaround is to programmatically add the  SparseFeature stanzas in the inferred schema (i.e., by manipulating the protobuf) if you already know which features should be sparse. Would that work?

If your question is about TFT's behavior when these SparseFeatures are present, then this is a question for the TFT devs -- TFDV does not control that behavior.

**Comment by arghyaganguly** [comment]
Closing this as there has been no update for some time.Please feel free to reopen based on above comment trace.Thanks.
